name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
     branches:
      - master

jobs:
    build:
      name: Azure Pipeline
      runs-on: windows-latest
      steps:
        - name: Azure Pipelines Action
          uses: Azure/Pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/ATTUpskilling/PartsUnlimited
            azure-pipeline-name: 'ATTDevOps.gitapp'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
